In [4]:
import math 

print(math.pi)
print( math.sqrt(5) )

import numpy as np

print( np.BUFSIZE )

import matplotlib as mp



3.141592653589793
2.23606797749979
8192


In [5]:
import math as m
from math import sqrt
# def sqrt():
#     pass
print(m.sqrt(25))
print(sqrt(25))

5.0


In [7]:
import vergihesaplari

aracFiyati = 200_000
aracKategorisi = "lüks"
aracMh = 2500

print( "Araç son fiyatı: {}".format(
    vergihesaplari.sonFiyat(aracFiyati,aracKategorisi,aracMh)
) )

Araç son fiyatı: 556000.0


In [9]:
import ogrenciler.notu
from ogrenciler.notu import finalGerekli

print(ogrenciler.notu.finalGerekli(44))
print(finalGerekli(44))

54.0


In [ ]:
import sys , math , vergihesaplari
from math import sqrt
from math import *


In [15]:

import numpy as np
import pygame as pg

A = [
    [2,3],
    [1,4],
    [2,1]
]

nar = np.array(A)
C = nar.dot(nar.T)
print(C)



[[13 14  7]
 [14 17  6]
 [ 7  6  5]]
